#!/bin/sh

# Set file ownership
/bin/chown -R root:root /opt/howru
/bin/chmod 755 /etc/init.d/howru-scheduler
/bin/chown root:root /etc/init.d/howru-scheduler
/bin/chown root:root /lib/system/systemd/howru-api.service
/bin/chown root:root /lib/system/systemd/howru-scheduler.service
/bin/chmod 655 /lib/system/systemd/howru-api.service
/bin/chmod 655 /lib/system/systemd/howru-scheduler.service

# Enable service
systemctl daemon-reload
systemctl enable howru-scheduler
systemctl start howru-scheduler
systemctl enable howru-api.service
systemctl start howru-api.service

exit 0
