{
 "title": "Custom App",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Custom App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "almond_check_app_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "almond_check_app_average{hostname=\"app01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "almond_check_app_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Minium",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "almond_check_app_min", "legendFormat": "__auto" }
   ]
  },
  { "title": "Web app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Percentage of response errors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "almond_check_webapp_error_percentage{hostname=\"webapp01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests handled",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "almond_check_webapp_fine_requests{hostname=\"webapp01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Httpd request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "almond_check_httpd_time{hostname=\"webapp01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "httpd size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "almond_check_httpd_size{hostname=\"webapp01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Redis hitrate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "almond_check_redis_hitrate{hostname=\"redis01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "almond_check_redis_response_time{hostname=\"redis01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "RTA Ping",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "almond_check_ping_rta{hostname=~\"app01.demo.com|webapp01.demo.com|redis01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Check load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "almond_check_load_load1{hostname=~\"app01.demo.com|webapp01.demo.com|redis01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "almond_check_memory_memory_used{hostname=~\"app01.demo.com|webapp01.demo.com|redis01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "almond_check_cpu_stats_cpuuser{hostname=~\"app01.demo.com|webapp01.demo.com|redis01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Redpanda Almond topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Heartbeat request errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "almond_check_topic_heartbeat_request_errors",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "almond_check_topic_under_replicated_replicas",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "almond_check_topic_consumer_request_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "almond_check_topic_producer_request_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log written bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "almond_check_topic_log_written_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max offset",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "almond_check_topic_max_offset", "legendFormat": "__auto" }
   ]
  }
 ]
}