almond.api=true
almond.port=9090
almond.standalone=false
almond.useSSL=false
api.activeMods=modyaml.py
api.authType=basic
api.bindPort=8080
api.dataDir=/opt/almond/data
api.enableAliases=true
api.enableFile=true
api.enableGUI=false
api.enableMods=false
api.enableScraper=true
api.enableSSL=false
api.isContainer=true
api.isMetricsProxy=false
api.isProxy=false
api.metricsDir=/opt/almond/data/metrics
api.persistant2fa=false
api.useSSL=false
api.showDashboard=on
api.sslCertificate=/opt/almond/www/api/ssl/cert.pem
api.sslKey=/opt/almond/www/api/ssl/key.pem
api.startPage=status
api.stateType=supervisorctl
api.userFile=/etc/almond/users.conf
api.wsgi=true
data.jsonFile=monitor_data.json
data.yamlFile=monitor.yaml
data.metricsFile=monitor.metrics
data.metricsOutputPrefix=almond
data.saveOnExit=false
gardener.CleanUpTime=86400
plugins.declaration=/etc/almond/plugins.conf
plugins.directory=/opt/almond/plugins
scheduler.confDir=/etc/almond
scheduler.confFile=/etc/almond/almond.conf
scheduler.dataCacheTimeFrame=0
scheduler.dataDir=/opt/almond/data
scheduler.enableClearDataCache=false
scheduler.enableGardener=true
scheduler.enableKafkaExport=false
scheduler.enableKafkaId=false
scheduler.enableKafkaTag=false
scheduler.format=jsonprometheus
scheduler.gardenerRunInterval=43200
scheduler.gardenerScript=/opt/almond/gardener.py
scheduler.hostName=almond_nginx_sidecar
scheduler.initSleepMs=7000
scheduler.kafkaAvro=false
scheduler.logDir=/var/log/almond
scheduler.logPluginOutput=true
scheduler.logToStdout=false
scheduler.quickStart=true
scheduler.schemaName=almond-monitor-topic-value
scheduler.schemaRegistryUrl=http://localhost:8081
scheduler.sleepMs=5000
scheduler.storeDir=/opt/almond/data/metrics
scheduler.storeResults=true
scheduler.truncateLog=false
scheduler.truncateLogInterval=604800
scheduler.tuneTimer=false
scheduler.tunerCycle=15
scheduler.type=time
scheduler.useExternal=false
