version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8089:8080"
      - "5000:5000"
    volumes:
      - ./almondmonitor-realm.json:/opt/keycloak/data/import/keycloak-realm.json
      - ./almondmonitor-users-0.json:/opt/keycloak/data/import/keycloal-users-0.json
   # volumes:
   #   - ./keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json
