{
 "title": "Almond demo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "ALMOND APPLICATION MONITORING", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Redis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "almond_check_redis_hitrate{hostname=\"redis01.demo.com\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "almond_check_redis_response_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Custom app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "almond_check_app_current{hostname=\"app01.demo.com\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "almond_check_app_average{hostname=\"app01.demo.com\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "almond_check_app_max{hostname=\"app01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache httpd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "almond_check_httpd_size{hostname=\"webapp01.demo.com\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "almond_check_httpd_time{hostname=\"webapp01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache Access",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "almond_check_apache_accesses{hostname=\"webapp01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "almond_check_apache_bytesperreq{hostname=\"webapp01.demo.com\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "almond_check_apache_bytespersec{hostname=\"webapp01.demo.com\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "almond_check_apache_reqpersec{hostname=\"webapp01.demo.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Check load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "almond_check_load_load1", "legendFormat": "__auto" }
   ]
  }
 ]
}